### ISSUE TITLE
snap: Builds started to fail

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1048]
https://github.com/parca-dev/parca-agent/actions/runs/3497876186/jobs/5857631546

```
The 'snap' directory is meant specifically for snapcraft, but it contains
the following non-snapcraft-related paths:
- README.md

This is unsupported and may cause unexpected behavior. If you must store
these files within the 'snap' directory, move them to 'snap/local'
which is ignored by snapcraft.
Launching instance...
Traceback (most recent call last):
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/bases/buildd.py", line 515, in _setup_apt
    executor.execute_run(
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/lxd/lxd_instance.py", line 289, in execute_run
    return self.lxc.exec(
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/lxd/lxc.py", line 329, in exec
    return runner(final_cmd, **kwargs)  # pylint: disable=subprocess-run-check
  File "/snap/snapcraft/8567/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lxc', '--project', 'snapcraft', 'exec', 'local:snapcraft-parca-agent-on-amd64-for-amd64-10422[21](https://github.com/parca-dev/parca-agent/actions/runs/3497876186/jobs/5857631546#step:6:22)', '--', 'env', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'SNAPCRAFT_MANAGED_MODE=1', 'apt-get', 'update']' returned non-zero exit status 100.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/lxd/lxd_provider.py", line 126, in launched_environment
    instance = launch(
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/lxd/launcher.py", line 212, in launch
    base_configuration.setup(executor=instance)
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/bases/buildd.py", line 351, in setup
    self._setup_apt(executor=executor, deadline=deadline)
  File "/snap/snapcraft/8567/lib/python3.8/site-packages/craft_providers/bases/buildd.py", line 521, in _setup_apt
    raise BaseConfigurationError(
craft_providers.bases.errors.BaseConfigurationError: Failed to update apt cache.
* Command that failed: 'lxc --project snapcraft exec local:snapcraft-parca-agent-on-amd64-for-amd64-104[22](https://github.com/parca-dev/parca-agent/actions/runs/3497876186/jobs/5857631546#step:6:23)21 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAPCRAFT_MANAGED_MODE=1 apt-get update'
* Command exit code: 100
```

Any ideas? Anyone?

cc @jnsgruk (Let me know if you don't want to get pinged ☺️ )

**Comment by jnsgruk** [comment]
Hmm. That's odd. I've had issues with 22.04 on runners where docker is also installed - LXD and Docker sometimes fight over iptables and LXD containers end up with no outbound internet access.

AFK today but happy to take a look on Monday! It might work better if the runner is on Ubuntu Focal as a starter, and I could follow up with a change to make out functional on Jammy

**Comment by jnsgruk** [comment]
Yeh reading some GitHub issues, it looks like `ubuntu-latest` only started meaning 22.04 quite recently so we might have been bitten by the shift in underlying version
