### ISSUE TITLE
Failure to parca-agent

### ISSUE THREAD

**Issue by cuiweiqiang** [parca-dev/parca-agent#1769]
I want to start a binary exec in Linux, but I get some errors like this:

```bash
level=debug name=parca-agent ts=2023-06-16T05:02:05.93688625Z caller=cpu.go:233 msg="libbpf: Error loading .BTF into kernel: -22. BTF is optional, ignoring."
level=debug name=parca-agent ts=2023-06-16T05:02:05.937436165Z caller=cpu.go:233 msg="libbpf: map 'heap': created successfully, fd=8"
level=debug name=parca-agent ts=2023-06-16T05:02:06.04057302Z caller=cpu.go:233 msg="libbpf: map 'unwind_tables': created successfully, fd=9"
level=debug name=parca-agent ts=2023-06-16T05:02:06.052532107Z caller=cpu.go:233 msg="libbpf: map 'process_info': created successfully, fd=10"
level=debug name=parca-agent ts=2023-06-16T05:02:06.052569752Z caller=cpu.go:233 msg="libbpf: map 'programs': created successfully, fd=11"
level=debug name=parca-agent ts=2023-06-16T05:02:06.052640035Z caller=cpu.go:233 msg="libbpf: map 'debug_pids': created successfully, fd=12"
level=debug name=parca-agent ts=2023-06-16T05:02:06.069764652Z caller=cpu.go:233 msg="libbpf: map 'stack_traces': created successfully, fd=13"
level=debug name=parca-agent ts=2023-06-16T05:02:06.087966004Z caller=cpu.go:233 msg="libbpf: map 'dwarf_stack_traces': created successfully, fd=14"
level=debug name=parca-agent ts=2023-06-16T05:02:06.088422834Z caller=cpu.go:233 msg="libbpf: map 'stack_counts': created successfully, fd=15"
level=debug name=parca-agent ts=2023-06-16T05:02:06.090076293Z caller=cpu.go:233 msg="libbpf: map 'unwind_info_chunks': created successfully, fd=16"
level=debug name=parca-agent ts=2023-06-16T05:02:06.09011322Z caller=cpu.go:233 msg="libbpf: map 'percpu_stats': created successfully, fd=17"
level=debug name=parca-agent ts=2023-06-16T05:02:06.090146836Z caller=cpu.go:233 msg="libbpf: map 'events': created successfully, fd=18"
level=debug name=parca-agent ts=2023-06-16T05:02:06.090191623Z caller=cpu.go:233 msg="libbpf: map 'parca.rodata': skipped auto-creating..."
level=debug name=parca-agent ts=2023-06-16T05:02:06.090215219Z caller=cpu.go:233 msg="libbpf: failed to parse target BTF: -2"
level=debug name=parca-agent ts=2023-06-16T05:02:06.090224021Z caller=cpu.go:233 msg="libbpf: failed to perform CO-RE relocations: -2"
level=debug name=parca-agent ts=2023-06-16T05:02:06.09025984Z caller=cpu.go:233 msg="libbpf: failed to load object 'parca'"
level=error name=parca-agent ts=2023-06-16T05:02:06.090292443Z caller=cpu.go:284 msg="Could not create unwind info shards"
level=debug name=parca-agent ts=2023-06-16T05:02:06.090415376Z caller=panic.go:884 msg="profiler: stopped" err=null profiler=parca_agent_cpu
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a677fd]

goroutine 191 [running]:
github.com/aquasecurity/libbpfgo.(*Module).Close(0x0)
	github.com/aquasecurity/libbpfgo@v0.4.7-libbpf-1.2.0-b2e29a1/libbpfgo.go:412 +0x1d
panic({0x1dd7aa0, 0x3278b60})
	runtime/panic.go:890 +0x263
github.com/aquasecurity/libbpfgo.(*Module).GetProgram.func1(0x20bfa5c?, 0xb?)
	github.com/aquasecurity/libbpfgo@v0.4.7-libbpf-1.2.0-b2e29a1/libbpfgo.go:1099 +0x19
github.com/aquasecurity/libbpfgo.(*Module).GetProgram(0x0, {0x20bfa5c, 0xb})
	github.com/aquasecurity/libbpfgo@v0.4.7-libbpf-1.2.0-b2e29a1/libbpfgo.go:1099 +0x4a
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run(0xc00029a000, {0x239f8f8, 0xc0007600c0})
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:423 +0x96f
main.run.func11.1({0x239f8f8?, 0xc0007600c0?})
	github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:685 +0x42
runtime/pprof.Do({0x239f850?, 0xc0004a9090?}, {{0xc000190020?, 0x2?, 0x0?}}, 0xc0001e8ea0)
	runtime/pprof/runtime.go:44 +0xa3
main.run.func11()
	github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:684 +0x565
github.com/oklog/run.(*Group).Run.func1({0xc00015b080?, 0xc0001c5850?})
	github.com/oklog/run@v1.1.0/group.go:38 +0x2f
created by github.com/oklog/run.(*Group).Run
	github.com/oklog/run@v1.1.0/group.go:37 +0x69
```

My kernel version is `4.19.110-300.el7.x86_64`

```bash
Linux version 4.19.110-300.el7.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)) #1 SMP Mon Mar 16 16:30:13 UTC 2020
```

How to sovle this problem?

**Comment by kakkoyun** [comment]
@cuiweiqiang Thanks for reaching out. Could you specify the version of the parca-agent? Could you also please provide information about your current platform?

**Comment by cuiweiqiang** [comment]
> 

OK, I can add some details :

parca-agent version:

```bash
[@txyz_116_16 ~]# ./parca-agent --version
parca-agent, version 0.19.0 (commit: 4094583a4567e3061e0ab357f17e3109b0514e2c, date: 2023-04-26T14:19:53Z), arch: amd64
```

OS version:

```bash
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

Some packages:

```bash
Package clang-3.4.2-9.el7.x86_64 already installed and latest version
Package elfutils-libelf-0.176-5.el7.x86_64 already installed and latest version
Package elfutils-libelf-devel-0.176-5.el7.x86_64 already installed and latest version
Package zlib-devel-1.2.7-18.el7.x86_64 already installed and latest version
```

CPU info:

```bash
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
stepping	: 7
microcode	: 0x5002f01
cpu MHz		: 2900.001
cache size	: 28160 KB
physical id	: 0
siblings	: 40
core id		: 0
cpu cores	: 20
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit
bogomips	: 4200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by brancz** [comment]
This Kernel version is too old to work with Parca Agent. Parca Agent currently requires a 5.4 or newer Kernel.

**Comment by brancz** [comment]
Sounds good! Let us know how that goes!

**Comment by javierhonduco** [comment]
Your kernel needs BTF support as well. If the problem persists, could you share the output of `free -h` as well as the memory limits for Parca Agent if running in a cgroup?

**Comment by javierhonduco** [comment]
Closing this issue as the 4.x is unsupported. We test every commit on [these kernels](https://github.com/parca-dev/parca-agent/blob/6ae314e02e490fa14cf119da50ba2c599e27fcd7/kerneltest/vmtest.sh#L87) and in general 5.x and 6.x is supported as long as BTF is present.

Let us know if you need anything!

**Comment by dreamerlzl** [comment]
maybe there needs to be an update here?
https://www.parca.dev/docs/parca-agent/

**Comment by brancz** [comment]
Do you want to send a PR to fix it @dreamerlzl?
