### ISSUE TITLE
Add DWARF CFA opcode `0x2d`

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#2181]
```
panic: Encountered an unexpected DWARF CFA opcode: 0x2d

goroutine 265 [running]:
github.com/parca-dev/parca-agent/internal/dwarf/frame.lookupFunc(0x88?, 0x1b40f84?)
        github.com/parca-dev/parca-agent/internal/dwarf/frame/table.go:402 +0x348
github.com/parca-dev/parca-agent/internal/dwarf/frame.executeDwarfInstruction(0x400308a0f0)
        github.com/parca-dev/parca-agent/internal/dwarf/frame/table.go:309 +0x84
github.com/parca-dev/parca-agent/internal/dwarf/frame.(*InstructionContextIterator).Next(0x40009ad060)
        github.com/parca-dev/parca-agent/internal/dwarf/frame/table.go:90 +0x5c
github.com/parca-dev/parca-agent/pkg/stack/unwind.BuildCompactUnwindTable({0x4000648800, 0x8f9, 0x900?}, 0xfba0?)
        github.com/parca-dev/parca-agent/pkg/stack/unwind/compact_unwind_table.go:157 +0x2c8
github.com/parca-dev/parca-agent/pkg/stack/unwind.GenerateCompactUnwindTable({0x4000c14520?, 0x4b0?})
        github.com/parca-dev/parca-agent/pkg/stack/unwind/compact_unwind_table.go:283 +0x60
github.com/parca-dev/parca-agent/pkg/profiler/cpu/bpf/maps.(*Maps).setUnwindTableForMapping(0x40006b1080, 0x2f?, 0x1d95280?, 0x40015591d0)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/bpf/maps/maps.go:1634 +0xae8
github.com/parca-dev/parca-agent/pkg/profiler/cpu/bpf/maps.(*Maps).AddUnwindTableForProcess(0x40006b1080, 0x1167bd, 0x0, {0x0, 0x0, 0x0}, 0x1)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/bpf/maps/maps.go:1288 +0x510
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).addUnwindTableForProcess(0x400017ee00, {0x29144c0, 0x4002314960}, 0xffffffffffffffff?)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:388 +0x6d0
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run.func1({0x4000c0e4f0, 0x1, 0x0?})
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:705 +0x5c
github.com/parca-dev/parca-agent/pkg/profiler/cpu.onDemandUnwindInfoBatcher({0x29144c0, 0x4002314960}, 0x4002dadf80, 0x472724?, 0x4002fd61e0)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:544 +0x180
created by github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run in goroutine 232
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:703 +0x1114
```

**Comment by javierhonduco** [comment]
`0x2d` is `DW_CFA_GNU_window_save`

**Comment by javierhonduco** [comment]
We need this opcode for return address signing (see https://reviews.llvm.org/D142572). We might need to add support for the signatures themselves, too. 

Related PR https://github.com/parca-dev/parca-agent/pull/787, turns out it's not specific to SPARC :D
