### ISSUE TITLE
python: Process detection not working for dynamically linked Python

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#2257]
```
$ ls /usr/lib/debug/usr/lib64/
libpython3.11d.so.1.0-3.11.5-1.el8_9.x86_64.debug  libpython3.11d.so.1.0-3.11.5-1.el8_9.x86_64.debug-gdb.py  libpython3.11.so.1.0-3.11.5-1.el8_9.x86_64.debug  libpython3.11.so.1.0-3.11.5-1.el8_9.x86_64.debug-gdb.py    __pycache__  python3.11
```

**Comment by javierhonduco** [comment]
This is for situations where `lib{ruby,python}.so` have an empty ELF symbol table? In that case, I wonder how things work at all, because I would have expected the dynamic linker to need symbols to be able to load the symbols and data that these libraries export 🤔

**Comment by javierhonduco** [comment]
Updated title to reflect the root cause

**Comment by javierhonduco** [comment]
Will close once @ethervoid can confirm if this fixes the issue he was seeing :)

**Comment by ethervoid** [comment]
@javierhonduco I'm getting this error deploying that change

```
panic: runtime error: invalid memory address or nil pointer dereference	8acf41844a3d42418c2956f82d40afa3	parca-agent
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cdc15a]	8acf41844a3d42418c2956f82d40afa3	parca-agent
goroutine 225 [running]:	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/pkg/pprof.(*Converter).addInterpreterLocation(0xc00257cf00, 0x2d6aea32f8379a)	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/pkg/pprof/pprof.go:309 +0x7a	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/pkg/pprof.(*Converter).Convert(0xc00257cf00, {0xbc52b9774?, 0x3e5d6e0?}, {0xc0007e8400, 0x22, 0x2459388?})	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/pkg/pprof/pprof.go:209 +0xb8f	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run(0xc0000fea80, {0x2b21690, 0xc002504060})	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:877 +0x1ec7	8acf41844a3d42418c2956f82d40afa3	parca-agent
main.run.func17.1({0x2b21690?, 0xc002504060?})	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:1134 +0x3b	8acf41844a3d42418c2956f82d40afa3	parca-agent
runtime/pprof.Do({0x2b216c8?, 0xc000792190?}, {{0xc002508000?, 0x2?, 0x0?}}, 0xc00008dec0)	8acf41844a3d42418c2956f82d40afa3	parca-agent
runtime/pprof/runtime.go:51 +0x9d	8acf41844a3d42418c2956f82d40afa3	parca-agent
main.run.func17()	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:1133 +0x4ec	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/oklog/run.(*Group).Run.func1({0xc0024ce300?, 0xc000a821c0?})	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/oklog/run@v1.1.0/group.go:38 +0x29	8acf41844a3d42418c2956f82d40afa3	parca-agent
created by github.com/oklog/run.(*Group).Run in goroutine 1	8acf41844a3d42418c2956f82d40afa3	parca-agent
github.com/oklog/run@v1.1.0/group.go:37 +0x67
```

**Comment by javierhonduco** [comment]
Is it possible that this stacktrace is missing some lines?

https://github.com/parca-dev/parca-agent/blob/841a9a4d8af5f484e32df5c3766e3f8ddb568770/pkg/pprof/pprof.go#L309

I would expect to see either `addFunction()` or `FullName()` as the top frame (`c` shouldn't be nil`)

**Comment by ethervoid** [comment]
This is all the log I have

```
[33mooooooooo.                                                  .o.                                            .[0m
[33m`888   `Y88.                                               .888.                                         .o8[0m
[33m 888   .d88'  .oooo.   oooo d8b  .ooooo.   .oooo.         .8"888.      .oooooooo  .ooooo.  ooo. .oo.   .o888oo[0m
[33m 888ooo88P'  `P  )88b  `888""8P d88' `"Y8 `P  )88b       .8' `888.    888' `88b  d88' `88b `888P"Y88b    888[0m
[33m 888          .oP"888   888     888        .oP"888      .88ooo8888.   888   888  888ooo888  888   888    888[0m
[33m 888         d8(  888   888     888   .o8 d8(  888     .8'     `888.  `88bod8P'  888    .o  888   888    888 .[0m
[33mo888o        `Y888""8o d888b    `Y8bod8P' `Y888""8o   o88o     o8888o `8oooooo.  `Y8bod8P' o888o o888o   "888"[0m
[33m                                                                      d"     YD[0m
[33m                                                                      "Y88888P'[0m
[33m[0m
level=info name=parca-agent ts=2023-11-20T11:46:44.250910139Z caller=main.go:509 msg="maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined"
level=info name=parca-agent ts=2023-11-20T11:46:44.357325456Z caller=main.go:553 msg="no config file provided, using default config"
level=info name=parca-agent ts=2023-11-20T11:46:44.363432701Z caller=main.go:611 msg="eBPF is supported and enabled by the host kernel"
name=parca-agent ts=2023-11-20T11:46:44.364829992Z caller=main.go:739 msg=starting... node=ip-172-30-36-152.ec2.internal store=grpc.polarsignals.com:443
level=info name=parca-agent ts=2023-11-20T11:46:44.372770429Z caller=cpu.go:229 component=cpu_profiler msg="loaded pyperf BPF module"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cdc15a]
goroutine 225 [running]:
github.com/parca-dev/parca-agent/pkg/pprof.(*Converter).addInterpreterLocation(0xc00257cf00, 0x2d6aea32f8379a)
	github.com/parca-dev/parca-agent/pkg/pprof/pprof.go:309 +0x7a
github.com/parca-dev/parca-agent/pkg/pprof.(*Converter).Convert(0xc00257cf00, {0xbc52b9774?, 0x3e5d6e0?}, {0xc0007e8400, 0x22, 0x2459388?})
	github.com/parca-dev/parca-agent/pkg/pprof/pprof.go:209 +0xb8f
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run(0xc0000fea80, {0x2b21690, 0xc002504060})
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:877 +0x1ec7
main.run.func17.1({0x2b21690?, 0xc002504060?})
	github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:1134 +0x3b
runtime/pprof.Do({0x2b216c8?, 0xc000792190?}, {{0xc002508000?, 0x2?, 0x0?}}, 0xc00008dec0)
	runtime/pprof/runtime.go:51 +0x9d
main.run.func17()
	github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:1133 +0x4ec
github.com/oklog/run.(*Group).Run.func1({0xc0024ce300?, 0xc000a821c0?})
	github.com/oklog/run@v1.1.0/group.go:38 +0x29
created by github.com/oklog/run.(*Group).Run in goroutine 1
	github.com/oklog/run@v1.1.0/group.go:37 +0x67
level=error name=parca-agent ts=2023-11-20T11:47:48.4765783Z caller=main.go:366 msg="======================= unexpected error ======================="
level=error name=parca-agent ts=2023-11-20T11:47:48.476661713Z caller=main.go:367 msg="last stderr" last_stderr="level=info name=parca-agent ts=2023-11-20T11:46:44.250910139Z caller=main.go:509 msg=\"maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined\"\nlevel=info name=parca-agent ts=2023-11-20T11:46:44.357325456Z caller=main.go:553 msg=\"no config file provided, using default config\"\nlevel=info name=parca-agent ts=2023-11-20T11:46:44.363432701Z caller=main.go:611 msg=\"eBPF is supported and enabled by the host kernel\"\nname=parca-agent ts=2023-11-20T11:46:44.364829992Z caller=main.go:739 msg=starting... node=ip-172-30-36-152.ec2.internal store=grpc.polarsignals.com:443\nlevel=info name=parca-agent ts=2023-11-20T11:46:44.372770429Z caller=cpu.go:229 component=cpu_profiler msg=\"loaded pyperf BPF module\"\npanic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cdc15a]\n\ngoroutine 225 [running]:\ngithub.com/parca-dev/parca-agent/pkg/pprof.(*Converter).addInterpreterLocation(0xc00257cf00, 0x2d6aea32f8379a)\n\tgithub.com/parca-dev/parca-agent/pkg/pprof/pprof.go:309 +0x7a\ngithub.com/parca-dev/parca-agent/pkg/pprof.(*Converter).Convert(0xc00257cf00, {0xbc52b9774?, 0x3e5d6e0?}, {0xc0007e8400, 0x22, 0x2459388?})\n\tgithub.com/parca-dev/parca-agent/pkg/pprof/pprof.go:209 +0xb8f\ngithub.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run(0xc0000fea80, {0x2b21690, 0xc002504060})\n\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:877 +0x1ec7\nmain.run.func17.1({0x2b21690?, 0xc002504060?})\n\tgithub.com/parca-dev/parca-agent/cmd/parca-agent/main.go:1134 +0x3b\nruntime/pprof.Do({0x2b216c8?, 0xc000792190?}, {{0xc002508000?, 0x2?, 0x0?}}, 0xc00008dec0)\n\truntime/pprof/runtime.go:51 +0x9d\nmain.run.func17()\n\tgithub.com/parca-dev/parca-agent/cmd/parca-agent/main.go:1133 +0x4ec\ngithub.com/oklog/run.(*Group).Run.func1({0xc0024ce300?, 0xc000a821c0?})\n\tgithub.com/oklog/run@v1.1.0/group.go:38 +0x29\ncreated by github.com/oklog/run.(*Group).Run in goroutine 1\n\tgithub.com/oklog/run@v1.1.0/group.go:37 +0x67\n"
level=error name=parca-agent ts=2023-11-20T11:47:48.47668844Z caller=main.go:368 msg="================================================================"
level=error name=parca-agent ts=2023-11-20T11:47:48.476701618Z caller=main.go:370 msg="about to report error to server"
level=info name=parca-agent ts=2023-11-20T11:47:48.896795684Z caller=main.go:395 msg="report sent successfully"
```

**Comment by javierhonduco** [comment]
Oh I think I see the bug now, I always that Golang returns `nil` if a key isn't present in a map... Sorry about this!

**Comment by javierhonduco** [comment]
@ethervoid can you please try `ghcr.io/parca-dev/parca-agent:main-1700493682-73ec54cc?

**Comment by ethervoid** [comment]
Great I'm not having the issue but I'm getting this error instead 

```
level=error name=parca-agent ts=2023-11-20T16:02:25.604452381Z caller=info.go:483 component=process_info msg="upload mapping" err="failed to ensure debug information uploaded: failed to obtain reader for object file: file is already closed\nfile /proc/4821/root/opt/app-root/lib/python3.11/site-packages/xxhash/_xxhash.cpython-311-x86_64-linux-gnu.so is already closed (try increasing `--object-file-pool-size`) it was closed by: github.com/parca-dev/parca-agent/pkg/objectfile.callers (github.com/parca-dev/parca-agent/pkg/objectfile/object_file.go:136) /github.com/parca-dev/parca-agent/pkg/objectfile.(*ObjectFile).close (github.com/parca-dev/parca-agent/pkg/objectfile/object_file.go:120) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).onEvicted (github.com/parca-dev/parca-agent/pkg/objectfile/pool.go:173) /github.com/parca-dev/parca-agent/pkg/cache.NewLRUCacheWithEvictionTTL[...].func1 (github.com/parca-dev/parca-agent/pkg/cache/cache_with_ttl.go:176) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).removeElement (github.com/parca-dev/parca-agent/pkg/cache/lru/lru.go:122) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).removeOldest (github.com/parca-dev/parca-agent/pkg/cache/lru/lru.go:113) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).Add (github.com/parca-dev/parca-agent/pkg/cache/lru/lru.go:70) /github.com/parca-dev/parca-agent/pkg/cache.(*CacheWithEvictionTTL[...]).Add (github.com/parca-dev/parca-agent/pkg/cache/cache_with_ttl.go:211) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).NewFile (github.com/parca-dev/parca-agent/pkg/objectfile/pool.go:316) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).Open (github.com/parca-dev/parca-agent/pkg/objectfile/pool.go:221) /github.com/parca-dev/parca-agent/pkg/process.(*MapManager).NewUserMapping (github.com/parca-dev/parca-agent/pkg/process/maps.go:231) /github.com/parca-dev/parca-agent/pkg/process.(*MapManager).MappingsForPID (github.com/parca-dev/parca-agent/pkg/process/maps.go:164) /github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).fetch (github.com/parca-dev/parca-agent/pkg/process/info.go:262) /github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).FetchWithFreshMappings (github.com/parca-dev/parca-agent/pkg/process/info.go:227) /github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).fetchProcessInfoWithFreshMappings (github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:465) /github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).listenEvents.func2 (github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:383) /runtime.goexit (runtime/asm_amd64.s:1650) /" buildid=3084e599620509132fedbeadf975937ece4a82fe filepath=/proc/4821/root/opt/app-root/lib/python3.11/site-packages/xxhash/_xxhash.cpython-311-x86_64-linux-gnu.so
```

Also I cannot see the symbols in the flamegraph yet

![Screenshot from 2023-11-20 17-24-36](https://github.com/parca-dev/parca-agent/assets/741240/e891a5f0-9254-4b19-846a-cdc35cc23bf7)

**Comment by ethervoid** [comment]
And this error too 

```
level=warn name=parca-agent ts=2023-11-20T16:32:28.439429753Z caller=batch_remote_write_client.go:135 msg="batch write client failed to send profiles" count=14 err="rpc error: code = Unimplemented desc = unknown service polarsignals.storage.v1alpha1.ColumnarStoreService"
```

**Comment by javierhonduco** [comment]
cc @kakkoyun about the first one. Reporting the second one internally so the backend team can take a look. Thanks a lot again for the reports!

**Comment by javierhonduco** [comment]
> Also I cannot see the symbols in the flamegraph yet

I assume that you mean that no Python stacks show up in the profile, right?

**Comment by ethervoid** [comment]
> I assume that you mean that no Python stacks show up in the profile, right?

Yes but finally I was able to find my App stacks which took me a while. I tried using the legend and zooming and finally I was able to find it

**Comment by brancz** [comment]
You managed to hit exactly the time where we rolled out a very major change in the infrastructure, that caused a few failed requests, let me know if you continue to see this error.

**Comment by brancz** [comment]
And you can only view python stacks using the runtime filter.

https://github.com/parca-dev/parca-agent/assets/4546722/9b8a6e5b-41de-4c1d-9ef4-3ddf3854fbde

**Comment by ethervoid** [comment]
Great with the runtime filter I can see it much better, thank you!

**Comment by brancz** [comment]
(We'll soon be working on using the legend for filtering, which is I believe what you tried doing first as well)

**Comment by ethervoid** [comment]
Yes that was the case
