### ISSUE TITLE
Panic while attempting to profile Python

### ISSUE THREAD

**Issue by Garbett1** [parca-dev/parca-agent#2311]
**Describe the bug**
Parca-agent panics while attempting to profile a Python binary

**To Reproduce**
Can't replicate with a minimal example yet, but happens consistently with the specific binary.

**Expected behavior**
Ideally, getting the trace, but at least an error rather than a panic.

**Logs**
```panic: runtime error: index out of range [0] with length 0

goroutine 192 [running]:
github.com/parca-dev/parca-agent/pkg/runtime/python.interpreterExecutableFile.copyMemory({0xc000d94038, 0xc000ef2320, 0x5222, 0x202000, 0xc0000c6960}, 0xc000672a20?, {0x3ea73c0?, 0x28?, 0x242f800?})
        github.com/parca-dev/parca-agent/pkg/runtime/python/python.go:238 +0x28e
github.com/parca-dev/parca-agent/pkg/runtime/python.versionFromBSS(0xc0000c6a50)
        github.com/parca-dev/parca-agent/pkg/runtime/python/python.go:119 +0x233
github.com/parca-dev/parca-agent/pkg/runtime/python.newInterpreter({0xc000ef2280?, {{0x2467ec8?, 0x31?}, 0x90?}})
        github.com/parca-dev/parca-agent/pkg/runtime/python/python.go:560 +0x655
github.com/parca-dev/parca-agent/pkg/runtime/python.InterpreterInfo({0xc001f880c0?, {{0x2467ec8?, 0xc001199698?}, 0x10?}})
        github.com/parca-dev/parca-agent/pkg/runtime/python/python.go:588 +0x4b
github.com/parca-dev/parca-agent/pkg/runtime/interpreter.Fetch({0xc000000c00?, {{0x2467ec8?, 0xc000da7950?}, 0x80?}})
        github.com/parca-dev/parca-agent/pkg/runtime/interpreter/interpreter.go:43 +0x72
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).fetch(0xc000000c00, {0x2b2b1d0, 0xc000da7950}, 0x5222, 0x0)
        github.com/parca-dev/parca-agent/pkg/process/info.go:299 +0x807
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Fetch(0xc000000c00, {0x2b2b1d0, 0xc0024845d0}, 0xc000d8ab00?)
        github.com/parca-dev/parca-agent/pkg/process/info.go:218 +0x106
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).prefetchProcessInfo(0xc002510000, {0x2b2b1d0?, 0xc0024845d0?}, 0x2?)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:450 +0x4b
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).addUnwindTableForProcess(0xc002510000, {0x2b2b1d0, 0xc0024845d0}, 0x3?)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:532 +0x42c
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).onDemandUnwindInfoBatcher.func1({0xc001612d00, 0x5, 0x0?})
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:496 +0x65
github.com/parca-dev/parca-agent/pkg/profiler/cpu.processEventBatcher({0x2b2b1d0, 0xc0024845d0}, 0xc0000e4840, 0x0?, 0xc001199f80)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:583 +0x1ed
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).onDemandUnwindInfoBatcher(0xc000584fd0?, {0x2b2b1d0?, 0xc0024845d0?}, 0xc000580001?)
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:494 +0x57
created by github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run in goroutine 301
        github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:821 +0x14e9
   ```

**Software (please complete the following information):**
 - Parca Agent Version: ghcr.io/parca-dev/parca-agent:main-1701197345-d865974b

**Workload (please complete the following information):**
- Runtime (if applicable): Python 3.10.13

**Environment (please complete the following information):**
- Linux Distribution: COS
- Linux Version: `5.15.120+`
- Arch:  `amd64`
- Kubernetes Version (if applicable): `Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.13-gke.200", GitCommit:"f24d4fe14dcec505c2b37cc1e5b7024d971f6360", GitTreeState:"clean", BuildDate:"2023-08-25T09:26:18Z", GoVersion:"go1.20.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}`
- Container Runtime (if applicable): `containerd` 1.6.21 

**Additional context**

**Comment by javierhonduco** [comment]
https://github.com/parca-dev/parca-agent/pull/2312 should fix this issue, will share the container built off main if you want to test it out as soon as it's built

**Comment by Garbett1** [comment]
Happy to update to main whenever it's ready!

**Comment by javierhonduco** [comment]
Amazing, thanks for checking!!
