### ISSUE TITLE
Agent reports `panic: duplicate metrics collector registration attempted`

### ISSUE THREAD

**Issue by skunert** [parca-dev/parca-agent#2971]
I am attempting to run `parca-agent` without any flags 0.32.0 on an ubuntu server.

After a few seconds it crashes:
```
./parca-agent
WARN[0000] Failed to setup gRPC connection (try 1 of 5): failed to exit idle mode: passthrough: received empty target in Build()
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000d34aa0, {0xc00082a170?, 0x0?, 0x0?})
        github.com/prometheus/client_golang@v1.19.1/prometheus/registry.go:405 +0x66
github.com/parca-dev/parca-agent/flags.FlagsRemoteStore.setupGrpcConnection({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x2540be400, 0x0, ...}, ...)
        github.com/parca-dev/parca-agent/flags/grpc.go:110 +0x92b
github.com/parca-dev/parca-agent/flags.FlagsRemoteStore.WaitGrpcEndpoint({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x2540be400, 0x0, ...}, ...)
        github.com/parca-dev/parca-agent/flags/grpc.go:35 +0x148
main.mainWithExitCode()
        github.com/parca-dev/parca-agent/main.go:163 +0xa1b
main.main()
        github.com/parca-dev/parca-agent/main.go:94 +0x13
```

**Comment by gites** [comment]
I'm observing the same. In my case it's happening when Parca server is not yet available (after restart) and Parca Agent(s) are trying to connect. When Parca server is up this is no longer happening. I'm running server in  K8s statefulSet and Agents daemonSet.
Parca v0.22
Parca Agent v0.32
  
```
time="2024-09-06T11:14:39Z" level=warning msg="Failed to setup gRPC connection (try 1 of 5): context deadline exceeded: connection error: desc = \"transport: Error while dialing: dial tcp 10.100.33.193:7070: connect: connection refused\""
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc00083f950, {0xc00086e760?, 0x0?, 0x0?})
        github.com/prometheus/client_golang@v1.19.1/prometheus/registry.go:405 +0x66
github.com/parca-dev/parca-agent/flags.FlagsRemoteStore.setupGrpcConnection({{0xc000a5c080, 0xa}, {0x0, 0x0}, {0x0, 0x0}, 0x1, 0x0, 0x2540be400, 0x0, ...}, ...)
        github.com/parca-dev/parca-agent/flags/grpc.go:110 +0x92b
github.com/parca-dev/parca-agent/flags.FlagsRemoteStore.WaitGrpcEndpoint({{0xc000a5c080, 0xa}, {0x0, 0x0}, {0x0, 0x0}, 0x1, 0x0, 0x2540be400, 0x0, ...}, ...)
        github.com/parca-dev/parca-agent/flags/grpc.go:35 +0x148
main.mainWithExitCode()
        github.com/parca-dev/parca-agent/main.go:163 +0xa1b
main.main()
        github.com/parca-dev/parca-agent/main.go:94 +0x13
```

**Comment by brancz** [comment]
Thank you for reporting! @umanwizard can you take a look on Monday?
