### ISSUE TITLE
Build with sanitizers

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#368]
As we use some C library wrappers and Golang can't prove the lifetime of objects at compile-time, it's possible that `parca-agent` is not memory safe.

It's very important that we have as many safeguards as possible as we run in privileged mode which we need to interact with the BPF subsystem.

Let's add memory sanitisers to `parca-agent`! 
 
- [ ] We can first start with dev builds with ASAN (will take a look at this)
- [ ] Adding it in CI (for example integration tests) next

**Comment by javierhonduco** [comment]
Trying now with

```patch
diff --git a/Makefile b/Makefile
index e00bbc8..e2cf2d5 100644
--- a/Makefile
+++ b/Makefile
@@ -77,7 +77,7 @@ go_env := GOOS=linux GOARCH=$(ARCH:x86_64=amd64) CC=$(CMD_CLANG) CGO_CFLAGS="-I
 ifndef DOCKER
 $(OUT_BIN): $(LIBBPF_HEADERS) $(LIBBPF_OBJ) $(filter-out *_test.go,$(GO_SRC)) $(BPF_BUNDLE) go/deps | $(OUT_DIR)
        find dist -exec touch -t 202101010000.00 {} +
-       $(go_env) go build -trimpath -v -o $(OUT_BIN) ./cmd/parca-agent
+       $(go_env) go build -asan -trimpath -v -o $(OUT_BIN) ./cmd/parca-agent
 else
 $(OUT_BIN): $(DOCKER_BUILDER) | $(OUT_DIR)
        $(call docker_builder_make,$@ VERSION=$(VERSION))
@@ -86,7 +86,7 @@ endif
 ifndef DOCKER
 $(OUT_BIN_DEBUG_INFO): go/deps
        find dist -exec touch -t 202101010000.00 {} +
-       go build -trimpath -v -o $(OUT_BIN_DEBUG_INFO) ./cmd/debug-info
+       go build -asan -trimpath -v -o $(OUT_BIN_DEBUG_INFO) ./cmd/debug-info
 else
 $(OUT_BIN_DEBUG_INFO): $(DOCKER_BUILDER) go/deps | $(OUT_DIR)
        $(call docker_builder_make,$@ VERSION=$(VERSION))
```

Reports:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==152265==ERROR: AddressSanitizer: BUS on unknown address (pc 0x000200800001 bp 0xffff88f9e530 sp 0xffff88f9e530 T2)
==152265==The signal is caused by a READ memory access.
==152265==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x200800001  (<unknown module>)
    #1 0x1f5ffac in _cgo_bf053d5b1c7b_Cfunc_bpf_link__destroy (/home/vagrant/work/parca-agent/dist/parca-agent+0x1f5ffac)
    #2 0x561678 in runtime.asmcgocall.abi0 runtime/asm_arm64.s:1060

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS (<unknown module>)
```

This is likely the error we saw in https://github.com/parca-dev/parca-agent/pull/367. I should have started with enabling sanitisers 😁
